version: '3'
services:
  clientesapp:
    container_name: clientes
    build:
      context: .
      dockerfile: project/Dockerfile
    ports:
      - "8004:8004"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=dbClientes
    depends_on:
      - dbClientes
    networks:
      - app-network

  dbClientes:
    container_name: dbClientes
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5435"
    networks:
      - app-network

networks:
  app-network:
    external: true